services:
  endee:
    image: endeeio/endee-server:latest
    container_name: endee-server
    ports:
      - "8080:8080"
    ulimits:
      nofile: 100000
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
    environment:
      NDD_NUM_THREADS: 0          # 0 = auto-detect
      NDD_AUTH_TOKEN: ""          # optional — set a secret string to enable auth
    volumes:
      - endee-data:/data
    restart: unless-stopped

volumes:
  endee-data:
